### ISSUE TITLE
CODE REVIEW: Readme

### ISSUE THREAD

**Issue by Psydwinder** [fac26/week3-authentification-dgkg#52]
Hey everyone, 

There is no information about seeding the project.

**Comment by Psydwinder** [comment]
Hey again,

It might also be a good idea to add a SCHEMA or a screenshot of how your tables look. 

It might also be worth adding in a link to a figma design or sketch to show how the end product is supposed to look

It might also be worth adding instructions for windows users who haven't got WSL working on their machine on how to run dev and run seed. 

**REMEMBER** you could add this into the package.json file as dev-win and seed-win

**Comment by ko-karol** [comment]
K. Will consider.
