### ISSUE TITLE
CODE REVIEW: Broken link

### ISSUE THREAD

**Issue by Psydwinder** [fac26/week3-authentification-dgkg#53]
Hey everyone, the deployed website link in your read me takes you page with a 404 error

![image](https://user-images.githubusercontent.com/101563800/216110850-492dd23d-f4c3-45fb-aa0c-b89c10dbedc9.png)

**Comment by georgiaewhitney** [comment]
Thanks for spotting, Niete! This has been corrected in the README - (about to be pushed down)
