### ISSUE TITLE
Bikes Bikes Bikes 💯 

### ISSUE THREAD

**Issue by Joe-Lindie** [fac26/week3-authentification-dgkg#56]
Hey, great job!

Perhaps consider changing the `type="text"` to  `type="password"` here. It will then render the password input field with `***` instead of `text` 

https://github.com/fac26/week3-authentification-dgkg/blob/645108588f1da3e48e88a8f981f4c2a86ac4781d/src/templates.js#L45

**Comment by ko-karol** [comment]
Good tip. Forgot about this.
