### ISSUE TITLE
Input field values

### ISSUE THREAD

**Issue by patdel0** [fac26/week3-authentification-dgkg#59]
![image](https://user-images.githubusercontent.com/53922624/216124279-4395e7c5-c6db-4994-b696-e9aa3e457297.png)

**Comment by ko-karol** [comment]
I swear it's already sanitized. :eyes: https://github.com/fac26/week3-authentification-dgkg/actions/runs/4067129424/jobs/7004092815

**Comment by patdel0** [comment]
> I swear it's already sanitized. 👀 https://github.com/fac26/week3-authentification-dgkg/actions/runs/4067129424/jobs/7004092815

HAHAHAHAHAHFLAKJVLKAHHAHAHAHAHALKVZLXCVZXCV
